import Link from 'next/link';
import { ChevronRight, FileText, Shield, CreditCard, Box, Scale } from 'lucide-react';
import LegalSidebar from '@/components/legal/LegalSidebar';

export default function TermsAndConditionsPage() {
  const lastUpdated = "March 26, 2026";

  const sections = [
    {
      id: "introduction",
      icon: <FileText className="w-5 h-5 text-orange-500" />,
      title: "1. Introduction and Scope",
      content: [
        "Welcome to PCB GLOBE. These Terms and Conditions (\"Terms\") govern your access to and use of the PCB GLOBE platform, including our website, instant quoting tools, and procurement services for Printed Circuit Board (PCB) fabrication, assembly, and component sourcing.",
        "By registering an account, uploading Gerber/BOM files, or placing an order, you agree to comply with and be bound by these Terms. If you do not agree to these Terms, you must not use our services."
      ]
    },
    {
      id: "account",
      icon: <Shield className="w-5 h-5 text-orange-500" />,
      title: "2. Account Registration and Business Verification",
      content: [
        "Users may browse public sections of the platform without an account. However, accessing the instant quoting engine, procuring components, or managing projects requires a registered PCB GLOBE account.",
        "To utilize enterprise services such as net payment terms or statement of accounts, users must complete the 'Business Account' verification process. We reserve the right to verify the provided DBA, Tax ID, and personnel information before granting enterprise privileges. You are responsible for maintaining the confidentiality of your login credentials."
      ]
    },
    {
      id: "orders",
      icon: <Box className="w-5 h-5 text-orange-500" />,
      title: "3. Quoting, Manufacturing, and Tolerances",
      content: [
        "All quotes generated by our automated platform are subject to a final manufacturability review. Prices and lead times are estimates based on the design parameters you input and the uploaded Gerber/BOM files.",
        "PCB GLOBE manufactures strictly according to IPC-A-600 Class 2 standards unless explicitly quoted otherwise. We are not responsible for design flaws, incorrect footprints, or electrical failures inherent in the design files provided by the customer. Any physical deviations within standard industry tolerances are acceptable and do not constitute a defect."
      ]
    },
    {
      id: "payment",
      icon: <CreditCard className="w-5 h-5 text-orange-500" />,
      title: "4. Payments, Cancellations, and Returns",
      content: [
        "Payment is required upfront at the time of order placement via secure portal unless a verified Business Account with approved Net Terms is utilized. All transactions are securely processed.",
        "Due to the custom nature of PCB manufacturing and assembly, orders cannot be cancelled once tooling or material procurement has commenced. If a manufacturing defect attributable to PCB GLOBE is discovered, you must notify support within 14 days of receipt to initiate an RMA (Return Merchandise Authorization) review. We do not accept returns for user design errors."
      ]
    },
    {
      id: "liability",
      icon: <Scale className="w-5 h-5 text-orange-500" />,
      title: "5. Limitation of Liability",
      content: [
        "PCB GLOBE shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use or inability to use our services, including product delays, loss of data, or loss of profits.",
        "Our maximum total liability to you for any claim arising out of your order shall not exceed the total amount paid by you for the specific order giving rise to the claim."
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50/50 pt-28 pb-32 selection:bg-orange-500/20">
      
      <div className="container mx-auto px-4 sm:px-6 max-w-[1400px]">
        
        {/* Breadcrumb Navigation */}
        <div className="flex items-center gap-2 text-[13px] font-bold text-gray-500 mb-8 max-w-6xl mx-auto animate-in fade-in slide-in-from-left-4 duration-500">
          <Link href="/" className="hover:text-[#ff6b00] transition-colors">Home</Link>
          <ChevronRight className="w-4 h-4 text-gray-400" />
          <span className="text-gray-900">Terms & Conditions</span>
        </div>

        <div className="flex flex-col lg:flex-row gap-10 max-w-6xl mx-auto">
          <LegalSidebar />
          
          <div className="flex-1">
            {/* Master Header Card */}
            <div className="bg-white p-10 md:p-14 rounded-[2rem] shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-gray-100 mb-10 overflow-hidden relative animate-in fade-in slide-in-from-bottom-8 duration-500">
          {/* Decorative Elements */}
          <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-orange-50 to-orange-100/50 rounded-bl-full -z-10 opacity-50 translate-x-10 -translate-y-10" />
          
          <div className="relative z-10">
            <h1 className="text-4xl md:text-5xl font-black text-gray-900 tracking-tight mb-4">
              Terms & Conditions
            </h1>
            <p className="text-[15px] font-semibold text-[#ff6b00] tracking-widest uppercase">
              Effective Date: {lastUpdated}
            </p>
            <p className="mt-6 text-gray-600 font-medium leading-relaxed max-w-2xl text-lg">
              Please carefully review the following rules and guidelines governing the use of the PCB GLOBE manufacturing platform, electronic quoting, and procurement services.
            </p>
          </div>
        </div>

        {/* Content Document */}
        <div className="bg-white p-8 md:p-14 rounded-[2rem] shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-gray-100 animate-in fade-in slide-in-from-bottom-12 duration-700 delay-100">
          <div className="space-y-12">
            
            {sections.map((section, idx) => (
              <section key={section.id} className="relative">
                {/* Section Header */}
                <div className="flex items-center gap-4 mb-5">
                  <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center border border-orange-100 shrink-0">
                    {section.icon}
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900">
                    {section.title}
                  </h2>
                </div>
                
                {/* Section Body */}
                <div className="pl-14 space-y-4">
                  {section.content.map((paragraph, pIdx) => (
                    <p key={pIdx} className="text-gray-600 leading-[1.8] font-medium text-[15px]">
                      {paragraph}
                    </p>
                  ))}
                </div>
                
                {/* Divider (except last) */}
                {idx !== sections.length - 1 && (
                  <div className="ml-14 mt-12 h-px bg-gray-100 w-full max-w-2xl" />
                )}
              </section>
            ))}

          </div>

          {/* Footer Callout */}
          <div className="mt-16 bg-gray-50 border border-gray-200 rounded-2xl p-8 text-center flex flex-col items-center">
            <h3 className="text-lg font-bold text-gray-900 mb-2">Have questions about our terms?</h3>
            <p className="text-[15px] font-medium text-gray-500 mb-6">Our compliance and support team is ready to assist you.</p>
            <Link 
              href="/contact-us"
              className="h-12 px-8 bg-white border-2 border-gray-200 hover:border-[#ff6b00] hover:text-[#ff6b00] rounded-full text-[13px] font-black uppercase text-gray-700 transition-all active:scale-95 flex items-center justify-center transform focus:outline-none"
            >
              Contact Support
            </Link>
          </div>
        </div>
          </div>
        </div>

      </div>
    </div>
  );
}
