/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    media: Media;
    orders: Order;
    payments: Payment;
    categories: Category;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  roles?: 'admin' | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  clerkId: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  imageUrl?: string | null;
  billingAttentionTo?: string | null;
  billingMailStop?: string | null;
  billingPhone?: string | null;
  billingEmail?: string | null;
  billingAddress1?: string | null;
  billingAddress2?: string | null;
  billingCountry?: string | null;
  billingState?: string | null;
  billingCity?: string | null;
  billingPincode?: string | null;
  billingGstin?: string | null;
  billingCompanyName?: string | null;
  shippingAttentionTo?: string | null;
  shippingMailStop?: string | null;
  shippingPhone?: string | null;
  shippingEmail?: string | null;
  shippingAddress1?: string | null;
  shippingAddress2?: string | null;
  shippingCountry?: string | null;
  shippingState?: string | null;
  shippingCity?: string | null;
  shippingPincode?: string | null;
  shippingGstin?: string | null;
  shippingCompanyName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  projectName: string;
  user: number | User;
  status?:
    | (
        | 'pending_payment'
        | 'payment_success'
        | 'payment_failed'
        | 'cam_validation'
        | 'production'
        | 'qc'
        | 'shipped'
        | 'delivered'
      )
    | null;
  total: number;
  razorpayOrderId?: string | null;
  items?:
    | {
        productId?: string | null;
        name?: string | null;
        quantity?: number | null;
        price?: number | null;
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    name?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    state?: string | null;
    pincode?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  billingAddress?: {
    name?: string | null;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    state?: string | null;
    pincode?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  specs?: {
    width?: number | null;
    height?: number | null;
    layers?: number | null;
    quantity?: number | null;
    color?: string | null;
  };
  gerberFile?: (number | null) | Media;
  payment?: (number | null) | Payment;
  deliveryMethod?: ('shiprocket' | 'custom') | null;
  deliveryStatus?:
    | ('not_dispatched' | 'ready_to_ship' | 'picked_up' | 'in_transit' | 'out_for_delivery' | 'delivered' | 'cancelled')
    | null;
  trackingNumber?: string | null;
  courierName?: string | null;
  shiprocketOrderId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  razorpayPaymentId: string;
  razorpayOrderId: string;
  amount: number;
  status?: ('success' | 'failed' | 'pending') | null;
  user: number | User;
  order: number | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  brand: string;
  manufacturer?: string | null;
  mpn?: string | null;
  description?: string | null;
  basePartNumber?: string | null;
  stock?: number | null;
  price: number;
  rating?: number | null;
  pricingTiers?:
    | {
        qty: number;
        unitPrice: number;
        extPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Specific details for PCB fabrication products (optional)
   */
  pcbDetails?: {
    boardType?: ('rigid' | 'flex' | 'rigid-flex') | null;
    layers?: number | null;
    material?: string | null;
    thickness?: string | null;
    copperWeight?: string | null;
    surfaceFinish?: ('hasl' | 'hasl-lf' | 'enig' | 'osp') | null;
    soldermaskColor?: string | null;
    silkscreenColor?: string | null;
  };
  datasheet?: (number | null) | Media;
  images?: (number | Media)[] | null;
  image?: (number | null) | Media;
  category: number | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkId?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  imageUrl?: T;
  billingAttentionTo?: T;
  billingMailStop?: T;
  billingPhone?: T;
  billingEmail?: T;
  billingAddress1?: T;
  billingAddress2?: T;
  billingCountry?: T;
  billingState?: T;
  billingCity?: T;
  billingPincode?: T;
  billingGstin?: T;
  billingCompanyName?: T;
  shippingAttentionTo?: T;
  shippingMailStop?: T;
  shippingPhone?: T;
  shippingEmail?: T;
  shippingAddress1?: T;
  shippingAddress2?: T;
  shippingCountry?: T;
  shippingState?: T;
  shippingCity?: T;
  shippingPincode?: T;
  shippingGstin?: T;
  shippingCompanyName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  projectName?: T;
  user?: T;
  status?: T;
  total?: T;
  razorpayOrderId?: T;
  items?:
    | T
    | {
        productId?: T;
        name?: T;
        quantity?: T;
        price?: T;
        image?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        name?: T;
        address1?: T;
        address2?: T;
        city?: T;
        state?: T;
        pincode?: T;
        email?: T;
        phone?: T;
      };
  billingAddress?:
    | T
    | {
        name?: T;
        address1?: T;
        address2?: T;
        city?: T;
        state?: T;
        pincode?: T;
        email?: T;
        phone?: T;
      };
  specs?:
    | T
    | {
        width?: T;
        height?: T;
        layers?: T;
        quantity?: T;
        color?: T;
      };
  gerberFile?: T;
  payment?: T;
  deliveryMethod?: T;
  deliveryStatus?: T;
  trackingNumber?: T;
  courierName?: T;
  shiprocketOrderId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  razorpayPaymentId?: T;
  razorpayOrderId?: T;
  amount?: T;
  status?: T;
  user?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  manufacturer?: T;
  mpn?: T;
  description?: T;
  basePartNumber?: T;
  stock?: T;
  price?: T;
  rating?: T;
  pricingTiers?:
    | T
    | {
        qty?: T;
        unitPrice?: T;
        extPrice?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  pcbDetails?:
    | T
    | {
        boardType?: T;
        layers?: T;
        material?: T;
        thickness?: T;
        copperWeight?: T;
        surfaceFinish?: T;
        soldermaskColor?: T;
        silkscreenColor?: T;
      };
  datasheet?: T;
  images?: T;
  image?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}